cli_auth_credentials_store = "file"
check_for_update_on_startup = false

[tui]
status_line = ["model-with-reasoning", "weekly-limit", "context-remaining", "git-branch"]

[mcp_servers.kubernetes]
url = "http://localhost:8080/mcp"
enabled = true

[mcp_servers.grafana]
url = "http://localhost:18000/mcp"
enabled = true
